import { NextRequest, NextResponse } from 'next/server';
import { generateFullKundliReport, generateKundliReportHtml } from '@vedic-astro/astrology-engine';
import fs from 'fs';
import path from 'path';
import os from 'os';
import { execSync } from 'child_process';

function getChromePath(): string {
  const candidates = [
    'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe',
    'C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe',
    'C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe',
    'C:\\Program Files\\Microsoft\\Edge\\Application\\msedge.exe',
    '/usr/bin/google-chrome',
    '/usr/bin/chromium-browser',
    '/usr/bin/chromium'
  ];

  for (const c of candidates) {
    if (fs.existsSync(c)) return c;
  }
  return 'chrome';
}

export async function POST(req: NextRequest) {
  try {
    const body = await req.json().catch(() => ({}));
    const name = body.name || 'PANKAJ DADHICH';
    const gender = body.gender || 'Male';
    const dob = body.dob || '2002-02-01';
    const tob = body.tob || '06:55';
    const place = body.place || 'Kheri Seela, Rajasthan, India';
    const latitude = typeof body.latitude === 'number' ? body.latitude : 26.8956;
    const longitude = typeof body.longitude === 'number' ? body.longitude : 74.4630;

    // 1. Generate full 17-chapter data model
    const reportData = generateFullKundliReport(name, gender, dob, tob, latitude, longitude, place);

    // 2. Generate publication-grade HTML & CSS with vector SVG charts
    const reportHtml = generateKundliReportHtml(reportData);

    // 3. Write temp files
    const tmpDir = os.tmpdir();
    const fileId = `kundli_rep_${Date.now()}_${Math.random().toString(36).substring(2, 7)}`;
    const htmlPath = path.join(tmpDir, `${fileId}.html`);
    const pdfPath = path.join(tmpDir, `${fileId}.pdf`);

    fs.writeFileSync(htmlPath, reportHtml, 'utf8');

    // 4. Run Chrome headless print-to-pdf
    const chromePath = getChromePath();
    const cmd = `"${chromePath}" --headless --disable-gpu --no-pdf-header-footer --print-to-pdf="${pdfPath}" "${htmlPath}"`;
    execSync(cmd, { timeout: 45000 });

    if (!fs.existsSync(pdfPath)) {
      throw new Error('PDF output file was not generated by Chrome engine.');
    }

    const pdfBuffer = fs.readFileSync(pdfPath);

    // Also copy to workspace root so user has instant file access if desired
    try {
      const workspacePdf = path.resolve('d:/astrology', `REP_vedic_kundli_${name.replace(/\s+/g, '_')}.pdf`);
      fs.copyFileSync(pdfPath, workspacePdf);
      console.log(`Saved copy to workspace: ${workspacePdf}`);
    } catch (e) {
      console.warn('Could not copy to workspace root', e);
    }

    // Cleanup temp files asynchronously
    setTimeout(() => {
      try {
        if (fs.existsSync(htmlPath)) fs.unlinkSync(htmlPath);
        if (fs.existsSync(pdfPath)) fs.unlinkSync(pdfPath);
      } catch {}
    }, 60000);

    return new NextResponse(pdfBuffer, {
      status: 200,
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': `attachment; filename="Vedic_Kundli_Report_${encodeURIComponent(name)}.pdf"`,
        'Content-Length': pdfBuffer.length.toString()
      }
    });
  } catch (error: any) {
    console.error('Failed to generate Kundli PDF report:', error);
    return NextResponse.json(
      {
        success: false,
        error: {
          code: 'PDF_GENERATION_FAILED',
          message: error.message || 'Unknown error during PDF generation'
        }
      },
      { status: 500 }
    );
  }
}

export async function GET(req: NextRequest) {
  // Convenient GET request using query params or default native
  const { searchParams } = new URL(req.url);
  const name = searchParams.get('name') || 'PANKAJ DADHICH';
  const gender = searchParams.get('gender') || 'Male';
  const dob = searchParams.get('dob') || '2002-02-01';
  const tob = searchParams.get('tob') || '06:55';
  const place = searchParams.get('place') || 'Kheri Seela, Rajasthan, India';
  const lat = parseFloat(searchParams.get('lat') || '26.8956');
  const lng = parseFloat(searchParams.get('lng') || '74.4630');

  const reportData = generateFullKundliReport(name, gender, dob, tob, lat, lng, place);
  const reportHtml = generateKundliReportHtml(reportData);

  const tmpDir = os.tmpdir();
  const fileId = `kundli_rep_${Date.now()}`;
  const htmlPath = path.join(tmpDir, `${fileId}.html`);
  const pdfPath = path.join(tmpDir, `${fileId}.pdf`);

  fs.writeFileSync(htmlPath, reportHtml, 'utf8');

  const chromePath = getChromePath();
  const cmd = `"${chromePath}" --headless --disable-gpu --no-pdf-header-footer --print-to-pdf="${pdfPath}" "${htmlPath}"`;
  execSync(cmd, { timeout: 45000 });

  const pdfBuffer = fs.readFileSync(pdfPath);

  return new NextResponse(pdfBuffer, {
    status: 200,
    headers: {
      'Content-Type': 'application/pdf',
      'Content-Disposition': `attachment; filename="Vedic_Kundli_Report_${encodeURIComponent(name)}.pdf"`,
      'Content-Length': pdfBuffer.length.toString()
    }
  });
}
